tix-condenser:
  tix-api:
    https: false
    host: localhost
    port: 8080
  queues:
    receiving:
      name: server-condenser-test
  reports:
    path: /tmp/reports
---
spring:
  profiles: test
tix-condenser:
  tix-api:
    https: false
    host: localhost
    port: 8081
  queues:
    receiving:
      name: server-condenser-test
  reports:
    path: /tmp/reports
server:
  port: 0
---
spring:
  profiles: staging
tix-condenser:
  queues:
    receiving:
      name: server-condenser-staging
---
spring:
  profiles: production
tix-condenser:
  queues:
    receiving:
      name: server-condenser-prod
---